services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: bookreview_apache
    ports:
      - "80:80"
    volumes:
      - uploads_data:/var/www/html/uploads
    depends_on:
      - web
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookreview_web
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      DB_NAME: "bookreview_dev"
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "8000"
      SERVE_STATIC_FILES: "false"
      UPLOADS_DIR: "/app/uploads"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: bookreview_mongo
    command: ["--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' | grep 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

volumes:
  mongo_data:
  uploads_data:
